name: gemini-pushport

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pushport_workdir:/var/pushport-workdir
      - ~/service-account.json:/opt/service-account.json:ro

volumes:
  pushport_workdir:
